In [15]:
import os

directory = os.path.join('sample_data', 'california_housing_train.csv') # Output: sample_data/california_housing_train.csv

text_file = open(directory, "r") # Read

lines = text_file.readlines()

parsed_values = []

for index, line in enumerate(lines):
  split_columns = line.split(",")

  if index == 0:
    continue

  parsed_values.append([float(split_columns[0]), float(split_columns[1]), float(split_columns[2]), float(split_columns[3]), float(split_columns[4]), float(split_columns[5]), float(split_columns[6]), float(split_columns[7]), float(split_columns[8])])

In [8]:
columns = ['longitude', 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', 'population', 'households', 'median_income', 'median_house_value']

columns_analyzed = ['housing_median_age', 'total_rooms', 'total_bedrooms', 'population', 'households', 'median_income', 'median_house_value']

In [30]:
import numpy as np

def analyze_stats(values, column):
  column_index = columns.index(column)

  numbers = []

  for value in values:
    numbers.append(value[column_index])
  
  numbers = sorted(numbers)

  average = sum(numbers) / len(numbers)
  standard_deviation = np.std(numbers)
  q1 = np.percentile(numbers, 25)
  q2 = np.percentile(numbers, 50)
  q3 = np.percentile(numbers, 75)
  contains_zero_or_empty = 0 in numbers or None in numbers

  print("Angka terkecil untuk kolom " + column + " bernilai " + str(numbers[0]))
  print("Angka terbesar untuk kolom " + column + " bernilai " + str(numbers[len(numbers) - 1]))
  print("Mean untuk kolom " + column + " bernilai " + str(average))
  print("Standard deviation untuk kolom " + column + " bernilai " + str(standard_deviation))
  print("Q1 untuk kolom " + column + " bernilai " + str(q1))
  print("Q2 untuk kolom " + column + " bernilai " + str(q2))
  print("Q3 untuk kolom " + column + " bernilai " + str(q3))

  if contains_zero_or_empty:
    print("Kolom " + column + " mengandung nilai 0 atau kosong")
  else:
    print("Kolom " + column + " tidak mengandung nilai 0 atau kosong")

In [35]:
analyze_stats(parsed_values, 'housing_median_age')

for current_column in columns_analyzed:
  analyze_stats(parsed_values, current_column)
  print('\n')

Angka terkecil untuk kolom housing_median_age bernilai 1.0
Angka terbesar untuk kolom housing_median_age bernilai 52.0
Mean untuk kolom housing_median_age bernilai 28.58935294117647
Standard deviation untuk kolom housing_median_age bernilai 12.58656677218719
Q1 untuk kolom housing_median_age bernilai 18.0
Q2 untuk kolom housing_median_age bernilai 29.0
Q3 untuk kolom housing_median_age bernilai 37.0
Kolom housing_median_age tidak mengandung nilai 0 atau kosong
Angka terkecil untuk kolom housing_median_age bernilai 1.0
Angka terbesar untuk kolom housing_median_age bernilai 52.0
Mean untuk kolom housing_median_age bernilai 28.58935294117647
Standard deviation untuk kolom housing_median_age bernilai 12.58656677218719
Q1 untuk kolom housing_median_age bernilai 18.0
Q2 untuk kolom housing_median_age bernilai 29.0
Q3 untuk kolom housing_median_age bernilai 37.0
Kolom housing_median_age tidak mengandung nilai 0 atau kosong


Angka terkecil untuk kolom total_rooms bernilai 2.0
Angka terbesar untuk kolom total_rooms bernilai 37937.0
Mean untuk kolom total_rooms bernilai 2643.664411764706
Standard deviation untuk kolom total_rooms bernilai 2179.882954419519
Q1 untuk kolom total_rooms bernilai 1462.0
Q2 untuk kolom total_rooms bernilai 2127.0
Q3 untuk kolom total_rooms bernilai 3151.25
Kolom total_rooms tidak mengandung nilai 0 atau kosong


Angka terkecil untuk kolom total_bedrooms bernilai 1.0
Angka terbesar untuk kolom total_bedrooms bernilai 6445.0
Mean untuk kolom total_bedrooms bernilai 539.4108235294118
Standard deviation untuk kolom total_bedrooms bernilai 421.4870543548563
Q1 untuk kolom total_bedrooms bernilai 297.0
Q2 untuk kolom total_bedrooms bernilai 434.0
Q3 untuk kolom total_bedrooms bernilai 648.25
Kolom total_bedrooms tidak mengandung nilai 0 atau kosong


Angka terkecil untuk kolom population bernilai 3.0
Angka terbesar untuk kolom population bernilai 35682.0
Mean untuk kolom population bernilai 1429.5739411764705
Standard deviation untuk kolom population bernilai 1147.819198281884
Q1 untuk kolom population bernilai 790.0
Q2 untuk kolom population bernilai 1167.0
Q3 untuk kolom population bernilai 1721.0
Kolom population tidak mengandung nilai 0 atau kosong


Angka terkecil untuk kolom households bernilai 1.0
Angka terbesar untuk kolom households bernilai 6082.0
Mean untuk kolom households bernilai 501.2219411764706
Standard deviation untuk kolom households bernilai 384.50953125308496
Q1 untuk kolom households bernilai 282.0
Q2 untuk kolom households bernilai 409.0
Q3 untuk kolom households bernilai 605.25
Kolom households tidak mengandung nilai 0 atau kosong


Angka terkecil untuk kolom median_income bernilai 0.4999
Angka terbesar untuk kolom median_income bernilai 15.0001
Mean untuk kolom median_income bernilai 3.8835781000000007
Standard deviation untuk kolom median_income bernilai 1.9081003953032114
Q1 untuk kolom median_income bernilai 2.566375
Q2 untuk kolom median_income bernilai 3.5446
Q3 untuk kolom median_income bernilai 4.767
Kolom median_income tidak mengandung nilai 0 atau kosong


Angka terkecil untuk kolom median_house_value bernilai 14999.0
Angka terbesar untuk kolom median_house_value bernilai 500001.0
Mean untuk kolom median_house_value bernilai 207300.91235294117
Standard deviation untuk kolom median_house_value bernilai 115980.35304985354
Q1 untuk kolom median_house_value bernilai 119400.0
Q2 untuk kolom median_house_value bernilai 180400.0
Q3 untuk kolom median_house_value bernilai 265000.0
Kolom median_house_value tidak mengandung nilai 0 atau kosong